#!/usr/bin/python

### NETWORK OPCODES ###
MSG_NONE = 0
MSG_CLIENT_DATABLOCK = 1

MSG_CLIENT_MOVE_UPDATE = 2
MSG_SERVER_MOVE_CMD = 3

MSG_CLIENT_CREATE_CONTROL_OBJ = 4
MSG_SERVER_ASSIGN_HOST = 5
MSG_CLIENT_ENTER_LOBBY = 6